#!/bin/bash
# generate.sh — Pulls fresh git data from all project repos and injects into index.html
# Usage: cd ~/dashboard && ./generate.sh

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
HTML="$SCRIPT_DIR/index.html"

if [ ! -f "$HTML" ]; then echo "Error: index.html not found"; exit 1; fi

# Project repos (must match order in PROJECTS array in index.html)
REPOS=(
  "/Users/sarath/clinicflow"
  "/Users/sarath/Documents/Streets-Commons"
  "/Users/sarath/Documents/chiangmai-experience"
  "/Users/sarath/Documents/fujifilm-sales"
)
IDS=("myclinicdesk" "safestreets" "cmguide" "fujifilm")

# Build a JS snippet that updates git data
JS_SNIPPET="<script>/* AUTO-GENERATED by generate.sh — $(date '+%Y-%m-%d %H:%M') */\n"
JS_SNIPPET+="(function(){\n"

for i in "${!REPOS[@]}"; do
  REPO="${REPOS[$i]}"
  ID="${IDS[$i]}"

  if [ -d "$REPO/.git" ]; then
    BRANCH=$(git -C "$REPO" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
    LAST_DATE=$(git -C "$REPO" log -1 --format='%ai' 2>/dev/null | cut -d' ' -f1 || echo "—")
    LAST_MSG=$(git -C "$REPO" log -1 --format='%s' 2>/dev/null | head -c 80 | sed "s/'/\\\\'/g" || echo "—")
    MODIFIED=$(git -C "$REPO" diff --numstat 2>/dev/null | wc -l | tr -d ' ')
    UNTRACKED=$(git -C "$REPO" ls-files --others --exclude-standard 2>/dev/null | wc -l | tr -d ' ')

    # Recent commits (last 10)
    COMMITS="["
    while IFS='|' read -r hash date msg; do
      msg=$(echo "$msg" | sed "s/'/\\\\'/g" | head -c 70)
      COMMITS+="{hash:'${hash}',date:'${date}',msg:'${msg}'},"
    done < <(git -C "$REPO" log --format="%h|%ai|%s" -10 2>/dev/null | while IFS='|' read h d m; do echo "${h}|$(echo "$d" | cut -d' ' -f1)|${m}"; done)
    COMMITS+="]"

    JS_SNIPPET+="var p=PROJECTS.find(function(p){return p.id==='${ID}'});\n"
    JS_SNIPPET+="if(p){p.git.branch='${BRANCH}';p.git.lastDate='${LAST_DATE}';p.git.lastMsg='${LAST_MSG}';p.git.modified=${MODIFIED};p.git.untracked=${UNTRACKED};p.git.commits=${COMMITS};}\n"
  fi
done

JS_SNIPPET+="if(typeof render==='function')render();\n"
JS_SNIPPET+="})();\n</script>"

# Remove old auto-generated script block if present
sed -i '' '/AUTO-GENERATED by generate.sh/,/<\/script>/d' "$HTML"

# Inject before closing </body>
sed -i '' "s|</body>|${JS_SNIPPET}\n</body>|" "$HTML"

echo "Dashboard updated with fresh git data ($(date '+%H:%M:%S'))"
echo "Open: open $HTML"
